In [1]:
import numpy as np
import pandas as pd

In [2]:
date=pd.read_csv('dataset/Order.csv')
time=pd.read_csv('dataset/message.csv')

In [7]:
date.head()

         date  order
0  2023-01-01    100
1  2023-01-02    150
2  2023-01-03    200
3  2023-01-04    250
4  2023-01-05    300

In [8]:
time.head()

                  time              Msg
0  2023-01-01 00:00:00   Order Received
1  2023-01-01 01:00:00  Order Processed
2  2023-01-01 02:00:00    Order Shipped
3  2023-01-01 03:00:00  Order Delivered
4  2023-01-01 04:00:00  Order Completed

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    15 non-null     object
 1   order   15 non-null     int64
dtypes: int64(1), object(1)
memory usage: 372.0+ bytes

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    15 non-null     object
 1   Msg     15 non-null     object
dtypes: object(2)
memory usage: 372.0+ bytes

# 1. Working date

In [9]:
date['date']=pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    15 non-null     datetime64[ns]
 1   order   15 non-null     int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 372.0 bytes

In [12]:
# Extracing year
date['date_year']=date['date'].dt.year  # dt means datetime
date.sample(6)

         date  order  date_year
10 2020-01-01    130       2020
14 2020-01-05    290       2020
8  2019-01-04    260       2019
13 2020-01-04    240       2020
5  2019-01-01    120       2019
6  2019-01-02    180       2019

In [14]:
# Exreacting month
date['date_month']=date['date'].dt.month
date.sample(6)

         date  order  date_year  date_month
7  2019-01-03    220       2019           1
11 2020-01-02    160       2020           1
14 2020-01-05    290       2020           1
13 2020-01-04    240       2020           1
5  2019-01-01    120       2019           1
0  2023-01-01    100       2023           1

In [16]:
# Extracting the name Month
date['date_month_name']=date['date'].dt.month_name()
date.sample(6)

         date  order  date_year  date_month date_month_name
13 2020-01-04    240       2020           1         January
12 2020-01-03    210       2020           1         January
3  2023-01-04    250       2023           1         January
5  2019-01-01    120       2019           1         January
10 2020-01-01    130       2020           1         January
1  2023-01-02    150       2023           1         January

In [17]:
# Extracing day
date['date_day']=date['date'].dt.day
date.sample(6)

         date  order  date_year  date_month date_month_name  date_day
9  2019-01-05    310       2019           1         January         5
4  2023-01-05    300       2023           1         January         5
10 2020-01-01    130       2020           1         January         1
14 2020-01-05    290       2020           1         January         5
12 2020-01-03    210       2020           1         January         3
7  2019-01-03    220       2019           1         January         3

In [18]:
# Extracing day name
date['date_day_name']=date['date'].dt.day_name()
date.sample(6)

,date,order,date_year,date_month,date_month_name,date_day,date_day_name
0,2023-01-01,100,2023,1,January,1,Sunday
12,2020-01-03,210,2020,1,January,3,Friday
11,2020-01-02,160,2020,1,January,2,Thursday
5,2019-01-01,120,2019,1,January,1,Tuesday
2,2023-01-03,200,2023,1,January,3,Tuesday
6,2019-01-02,180,2019,1,January,2,Wednesday

# 2. Working time

In [20]:
time.head()

                  time              Msg
0  2023-01-01 00:00:00   Order Received
1  2023-01-01 01:00:00  Order Processed
2  2023-01-01 02:00:00    Order Shipped
3  2023-01-01 03:00:00  Order Delivered
4  2023-01-01 04:00:00  Order Completed

In [21]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    15 non-null     object
 1   Msg     15 non-null     object
dtypes: object(2)
memory usage: 372.0+ bytes

In [22]:
time['time']=pd.to_datetime(time['time'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    15 non-null     datetime64[ns]
 1   Msg     15 non-null     object
dtypes: datetime64[ns](1), object(1)
memory usage: 372.0+ bytes

In [24]:
time.head()

                 time              Msg
0 2023-01-01 00:00:00   Order Received
1 2023-01-01 01:00:00  Order Processed
2 2023-01-01 02:00:00    Order Shipped
3 2023-01-01 03:00:00  Order Delivered
4 2023-01-01 04:00:00  Order Completed

In [26]:
# Extracing hour and min, sec
time['hour']=time['time'].dt.hour
time['min']=time['time'].dt.minute
time['sec']=time['time'].dt.second

time.sample(6)

                  time              Msg  hour  min  sec
0  2023-01-01 00:00:00   Order Received     0    0    0
4  2023-01-01 04:00:00  Order Completed     4    0    0
1  2023-01-01 01:00:00  Order Processed     1    0    0
13 2023-01-03 03:00:00  Order Delivered     3    0    0
9  2023-01-02 04:00:00  Order Completed     4    0    0
10 2023-01-03 00:00:00   Order Received     0    0    0