In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [3]:
df=pd.read_csv('dataset/titanic.csv')
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [18]:

data=df.drop(columns=['PassengerId','Name','Sex','Ticket','Fare','Cabin','Embarked'],axis=True)
data.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [19]:
data.shape

(891, 5)

In [21]:
data=data.dropna()
data

     Survived  Pclass   Age  SibSp  Parch
0           0       3  22.0      1      0
1           1       1  38.0      1      0
2           1       3  26.0      0      0
3           1       1  35.0      1      0
4           0       3  35.0      0      0
..        ...     ...   ...    ...    ...
885         0       3  39.0      0      5
886         0       2  27.0      0      0
887         1       1  19.0      0      0
889         1       1  26.0      0      0
890         0       3  32.0      0      0

[714 rows x 5 columns]

In [22]:
data.isnull().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
dtype: int64

In [23]:
X=data.iloc[:,1:]
y=data.iloc[:,0]

In [24]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

# Applying Feature Constructing

In [25]:
X['Family_size']=X['SibSp']+X['Parch']+1

In [26]:
X.head()

   Pclass   Age  SibSp  Parch  Family_size
0       3  22.0      1      0            2
1       1  38.0      1      0            2
2       3  26.0      0      0            1
3       1  35.0      1      0            2
4       3  35.0      0      0            1

In [33]:
def myFucn(num):
    if num ==1:
        # alone
        return 0
    elif num >1 and num <=4:
        #small family 
        return 1
    else:
        # large Family
        return 2

In [34]:
print(myFucn(5))

2

In [37]:
X['Family_type']=X['Family_size'].apply(myFunc)

NameError: name 'myFunc' is not defined

In [36]:
X.head()

   Pclass   Age  SibSp  Parch  Family_size
0       3  22.0      1      0            2
1       1  38.0      1      0            2
2       3  26.0      0      0            1
3       1  35.0      1      0            2
4       3  35.0      0      0            1