In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("penguins_size.csv")
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [4]:
df.isnull().sum()

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [9]:
df['species'].isnull().sum()

np.int64(0)

In [5]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

In [10]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=42)

In [11]:
X_train

,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
66,Biscoe,35.5,16.2,195.0,3350.0,FEMALE
229,Biscoe,46.8,15.4,215.0,5150.0,MALE
7,Torgersen,39.2,19.6,195.0,4675.0,MALE
140,Dream,40.2,17.1,193.0,3400.0,FEMALE
323,Biscoe,49.1,15.0,228.0,5500.0,MALE
...,...,...,...,...,...,...
188,Dream,47.6,18.3,195.0,3850.0,FEMALE
71,Torgersen,39.7,18.4,190.0,3900.0,MALE
106,Biscoe,38.6,17.2,199.0,3750.0,FEMALE
270,Biscoe,46.6,14.2,210.0,4850.0,FEMALE
102,Biscoe,37.7,16.0,183.0,3075.0,FEMALE

In [12]:
y_train

66        Adelie
229       Gentoo
7         Adelie
140       Adelie
323       Gentoo
         ...
188    Chinstrap
71        Adelie
106       Adelie
270       Gentoo
102       Adelie
Name: species, Length: 275, dtype: object