In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [4]:
df=sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
enc=LabelEncoder()
df['species']=enc.fit_transform(df['species'])

In [6]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [8]:
x=df.iloc[:,0:4]
y=df.iloc[:,-1]

In [9]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12)

In [10]:
X_train.head()

     sepal_length  sepal_width  petal_length  petal_width
17            5.1          3.5           1.4          0.3
81            5.5          2.4           3.7          1.0
103           6.3          2.9           5.6          1.8
33            5.5          4.2           1.4          0.2
101           5.8          2.7           5.1          1.9

In [11]:
lg=LogisticRegression(multi_class='multinomial')

In [12]:
lg.fit(X_train,y_train)

C:\Users\91886\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\91886\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(multi_class='multinomial')

In [13]:
y_pred=lg.predict(X_test)

In [14]:
print(accuracy_score(y_pred,y_test))

0.9666666666666667

In [15]:
pd.DataFrame(confusion_matrix(y_pred,y_test))

    0  1  2
0  12  0  0
1   0  8  0
2   0  1  9

# Prediction

In [17]:
inp=np.array([[2.4,3.6,4.5,2.4]])
lg.predict_proba(inp)

C:\Users\91886\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[0.01643993, 0.0445127 , 0.93904737]])

In [18]:
lg.predict(inp)

C:\Users\91886\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([2])

In [19]:
from mlxtend.plotting import plot_decision_regions
plot_decision_regions(x.values,y.values,lg,legend=4)

# addind axes
plt.show()

ModuleNotFoundError: No module named 'mlxtend'